### ISSUE TITLE
Rails 3.1 has broken columns on demand

### ISSUE THREAD

**Issue by tlconnor** [willbryant/columns_on_demand#1]
Couple of issues:
1. class_inheritable_accessor has been deprecated in rails 3.1
2. Rails 3.1 includes the identity map so the process of loading columns information has changed, resulting in lazy loaded columns never being loaded

The first issue is easy enough to fix.  I've had a quick look into the second issue but haven't been able to determine exactly what is going wrong.

**Comment by willbryant** [comment]
Was resolved years ago, but forgot to close the issue.
